### ISSUE TITLE
Why is this not just part of GHC?

### ISSUE THREAD

**Issue by ocharles** [polysemy-research/loopbreaker#3]
Hi, great work on this research and this plugin! But why is it not just a patch to GHC? Are there any open tickets one can read for more info?

**Comment by isovector** [comment]
Good question! Our official GHC insiders suggest a plugin is the best step on that path --- write something in user code that we can show improves real-world performance, and then use that as leverage for getting the changes into GHC!

**Comment by ocharles** [comment]
Cool, makes sense. Thanks!
