### ISSUE TITLE
Bump GHC upper bound?

### ISSUE THREAD

**Issue by googleson78** [polysemy-research/loopbreaker#6]
Can we bump ghc's upper bound?
I tried to do so, and setting `resolver: nightly-2019-09-30` makes it compile just fine.
This bound is one of the reasons `polysemy` can't build with `nightly-2019-09-30` right now.

In fact looking at `polysemy`'s `package.yaml` - it only uses `loopbreaker` for `ghc >= 8.7`.. yet loopbreaker is set to specifically only compile with `ghc < 8.7`? I think I'm missing something here.

**Comment by TheMatten** [comment]
8.8.1 changelog says there was "further refinement of TTG representation" - but if it compiles fine, then we shouldn't be (hopefully) affected.

**Comment by googleson78** [comment]
I totally missed that there are tests! That's really cool actually!

I just tried to run them and they also seem to pass

**Comment by TheMatten** [comment]
@googleson78 Yeah, it feels somewhat weird to test this stuff :smile:
I'm wondering how should transition to current version of GHC [look like](https://github.com/polysemy-research/polysemy/issues/235#issuecomment-537113988) - let's wait until it's sorted out :slightly_smiling_face:

**Comment by googleson78** [comment]
For me it's less "this is weird" and more "it's really awesome that you can (and people bothered to) test something like this".

**Comment by TheMatten** [comment]
@googleson78 Weird as in _weirdly cool_ :smile: But at the end, we need to test this to make sure `loopbreaker` does what it says.

**Comment by isovector** [comment]
~I'm happy to bump the upper bound, but would prefer to do it in `.travis` instead of `stack.yaml`.~

Edit: just noticed this is `loopbreaker`, not `polysemy`.
